// Settings keys for all services
export enum SettingsKeyEnum {
  SMS_PROVIDER = "SMS_PROVIDER",
  SMS_ORIGINATOR = "SMS_ORIGINATOR",
  SMS_API_KEY = "SMS_API_KEY",
  SMS_VERIFICATION_CODE_PATTERN = "SMS_VERIFICATION_CODE_PATTERN",
  SMS_BIRTHDAY_CONGRATS = "SMS_BIRTHDAY_CONGRATS",
  SMS_BIRTHDAY_CONGRATS_TIME = "SMS_BIRTHDAY_CONGRATS_TIME",

  EMAIL_NEWSLETTER_SEND = "EMAIL_NEWSLETTER_SEND",
  EMAIL_NEWSLETTER_SEND_TIME = "EMAIL_NEWSLETTER_SEND_TIME",
  EMAIL_NEWSLETTER_HEADER = "EMAIL_NEWSLETTER_HEADER",
  EMAIL_NEWSLETTER_BODY = "EMAIL_NEWSLETTER_BODY",
  EMAIL_NEWSLETTER_FOOTER = "EMAIL_NEWSLETTER_FOOTER",

  COMMENT_IS_APPROVED = "COMMENT_IS_APPROVED",
  COMMENT_FORBIDDEN_EXPRESSIONS = "COMMENT_FORBIDDEN_EXPRESSIONS",
  COMMENT_FORBIDDEN_SUSPEND = "COMMENT_FORBIDDEN_SUSPEND",
  COMMENT_MAX_LENGTH = "COMMENT_MAX_LENGTH",

  FILE_URL_EXP_HOURS = "FILE_URL_EXPIRATION",
  FILE_WATERMARK_ACTIVE = "FILE_WATERMARK_ACTIVE",
  FILE_WATERMARK_IMAGE_ID = "FILE_WATERMARK_IMAGE_ID",
  FILE_WATERMARK_TO_IMAGE_DIMENSIONS = "FILE_WATERMARK_TO_IMAGE_DIMENSIONS",
  FILE_WATERMARK_PLACEMENT = "FILE_WATERMARK_PLACEMENT",
  FILE_WATERMARK_MARGINS_TOP = "FILE_WATERMARK_MARGINS_TOP",
  FILE_WATERMARK_MARGINS_RIGHT = "FILE_WATERMARK_MARGINS_RIGHT",
  FILE_WATERMARK_MARGINS_BOTTOM = "FILE_WATERMARK_MARGINS_BOTTOM",
  FILE_WATERMARK_MARGINS_LEFT = "FILE_WATERMARK_MARGINS_LEFT",
  FILE_WATERMARK_OPACITY = "FILE_WATERMARK_OPACITY",
  FILE_WATERMARK_SIZES = "FILE_WATERMARK_SIZES"
}