export enum SettingsServiceEnum {
  ACTIVITIES = "ACTIVITIES",
  LANGS = "LANGS",
  FILES = "FILES",
  USERS = "USERS",
  POSTS = "POSTS",
  COMMENTS = "COMMENTS",
  TAXONOMIES = "TAXONOMIES",
  SMS = "SMS",
  EMAIL = "EMAIL",
  NEWSLETTER = "NEWSLETTER",
  CONTACT = "CONTACT",
  GENERAL = "GENERAL"
}