export enum SettingsServiceEnum {
  ACTIVITIES = "ACTIVITIES",
  LANGS = "LANGS",
  FILES = "FILES",
  AUTH = "AUTH",
  POSTS = "POSTS",
  COMMENTS = "COMMENTS",
  TAXONOMIES = "TAXONOMIES",
  SMS = "SMS",
  EMAIL = "EMAIL"
}